[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc_version = '0.8.28'
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1

[profile.dev]
optimizer = false 
optimizer_runs = 0  
via_ir = false


[rpc_endpoints]
base = "${RPC_BASE}"
optimism = "${RPC_OP}"
mainnet = "${RPC_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
