[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc_version = '0.8.28'
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1
# useful for storage layout
libraries = ["@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20:0x0000000000000000000000000000000000000000"]

[profile.dev]
optimizer = false 
optimizer_runs = 0  
via_ir = false


[rpc_endpoints]
base = "${RPC_BASE}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
